apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-spot-cluster
  region: us-east-1

managedNodeGroups: # this is also completely managed by AWS
  - name: spot
    instanceType: t3.medium
    # your K8 node can be anytime taken back by AWS
    spot: true
    desiredCapacity: 3
